package Forms;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author julio
 */
import Forms.EditUsers;
import Forms.EditMovies;
import javax.swing.JOptionPane; 

public class AdminManagerScreens extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AdminManagerScreens.class.getName());

    /**
     * Creates new form AdminManagerScreens
     */
    public AdminManagerScreens() {
        initComponents();
        setLocationRelativeTo(null); // centrar ventana
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BtnCustomer = new javax.swing.JButton();
        BtnMovies = new javax.swing.JButton();
        BtnRentals = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BtnCustomer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/people.png"))); // NOI18N
        BtnCustomer.setText("Customer");
        BtnCustomer.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BtnCustomer.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BtnCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCustomerActionPerformed(evt);
            }
        });

        BtnMovies.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Movie.png"))); // NOI18N
        BtnMovies.setText("Movies");
        BtnMovies.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BtnMovies.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BtnMovies.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnMoviesActionPerformed(evt);
            }
        });

        BtnRentals.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Coke.jpg"))); // NOI18N
        BtnRentals.setText("Rentals");
        BtnRentals.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BtnRentals.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BtnRentals.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRentalsActionPerformed(evt);
            }
        });

        btnLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logoutBtnImg.png"))); // NOI18N
        btnLogout.setText("Logout");
        btnLogout.setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        btnLogout.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnLogout.setMaximumSize(new java.awt.Dimension(180, 168));
        btnLogout.setMinimumSize(new java.awt.Dimension(180, 168));
        btnLogout.setPreferredSize(new java.awt.Dimension(180, 168));
        btnLogout.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(BtnCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(BtnMovies, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addComponent(BtnRentals, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(BtnCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(BtnRentals, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnLogout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BtnMovies, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE)))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Nombre: BtnCustomerActionPerformed
    // Propósito: Abrir la pantalla de administración de usuarios (clientes) desde el menú de admin.
    // PreCondiciones: La clase EditUsers debe estar disponible y su constructor no debe fallar.
    // PostCondiciones: Se muestra la ventana EditUsers y se cierra la ventana actual de AdminManagerScreens.
    // Argumentos: evt - evento de clic del botón "Customer".
    // Valores: No devuelve valor.
    private void BtnCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCustomerActionPerformed
        // TODO add your handling code here:
    new EditUsers().setVisible(true);
    this.dispose();
        
    }//GEN-LAST:event_BtnCustomerActionPerformed

    // Nombre: BtnMoviesActionPerformed
    // Propósito: Abrir la pantalla de administración de películas desde el menú de admin.
    // PreCondiciones: La clase EditMovies debe existir y poder crearse.
    // PostCondiciones: Se abre la ventana EditMovies y se cierra AdminManagerScreens.
    // Argumentos: evt - evento de clic del botón "Movies".
    // Valores: No devuelve valor.
    private void BtnMoviesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnMoviesActionPerformed
        // TODO add your handling code here:
         new EditMovies().setVisible(true);
    this.dispose();

    }//GEN-LAST:event_BtnMoviesActionPerformed

    // Nombre: BtnRentalsActionPerformed
    // Propósito: Abrir la pantalla donde el admin maneja las rentas (ver, añadir y marcar devoluciones).
    // PreCondiciones: La clase EditRentals debe existir y conectarse correctamente con la base de datos.
    // PostCondiciones: Se abre la ventana EditRentals y se cierra la ventana AdminManagerScreens.
    // Argumentos: evt - evento de clic del botón "Rentals".
    // Valores: No devuelve valor.
    private void BtnRentalsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRentalsActionPerformed
        // TODO add your handling code here:
    new EditRentals().setVisible(true);
    this.dispose();
    }//GEN-LAST:event_BtnRentalsActionPerformed

    // Nombre: btnLogoutActionPerformed
    // Propósito: Cerrar la sesión del administrador y regresar a la pantalla de Login.
    // PreCondiciones: La clase LoginForm debe existir y ser accesible.
    // PostCondiciones: Se cierra AdminManagerScreens y se muestra la ventana de LoginForm.
    // Argumentos: evt - evento de clic del botón "Logout".
    // Valores: No devuelve valor.
    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        new LoginForm().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnLogoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new AdminManagerScreens().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCustomer;
    private javax.swing.JButton BtnMovies;
    private javax.swing.JButton BtnRentals;
    private javax.swing.JButton btnLogout;
    // End of variables declaration//GEN-END:variables
}
