/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Forms;

/**
 *
 * @author julio
 */
import database.DBConnection;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class EditUsers extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(EditUsers.class.getName());

    /**
     * Creates new form Users
     */
    public EditUsers() {
        initComponents();
        setLocationRelativeTo(null); // Centra la ventana
        loadUsers(); // Carga los usuarios al abrir
    }
    // Nombre: loadUsers
    // Propósito: Leer todos los usuarios de la base de datos y mostrarlos en la tabla tblUsers.
    // PreCondiciones: La conexión a la base de datos debe funcionar y el modelo de la tabla debe estar inicializado.
    // PostCondiciones: La tabla se limpia y se vuelve a llenar con los datos actuales de la tabla users.
    // Argumentos: Ninguno.
    // Valores: No devuelve valor, solo actualiza la interfaz con la información de los usuarios.
    private void loadUsers() {
    DefaultTableModel model = (DefaultTableModel) tblUsers.getModel();
    // Limpiar filas actuales
    model.setRowCount(0);

    String sql = "SELECT user_id, first_name, middle_name, last_name, " +
                 "phone, address, city, zip_code, birth_date " +
                 "FROM users ORDER BY user_id";

    try (Connection cn = DBConnection.getConnection();
         PreparedStatement ps = cn.prepareStatement(sql);
         ResultSet rs = ps.executeQuery()) {

        while (rs.next()) {
            Object[] row = new Object[9];
            row[0] = rs.getInt("user_id");
            row[1] = rs.getString("first_name");
            row[2] = rs.getString("middle_name");
            row[3] = rs.getString("last_name");
            row[4] = rs.getString("phone");
            row[5] = rs.getString("address");
            row[6] = rs.getString("city");
            row[7] = rs.getString("zip_code");
            row[8] = rs.getDate("birth_date");

            model.addRow(row);
        }

    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this,
                "Error cargando usuarios:\n" + e.getMessage());
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BtnAgregar = new javax.swing.JButton();
        BtnEditar = new javax.swing.JButton();
        BtnEliminar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblUsers = new javax.swing.JTable();
        btnAdminMenu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BtnAgregar.setText("Agregar");
        BtnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAgregarActionPerformed(evt);
            }
        });

        BtnEditar.setText("Editar");
        BtnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEditarActionPerformed(evt);
            }
        });

        BtnEliminar.setText("Eliminar");
        BtnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEliminarActionPerformed(evt);
            }
        });

        tblUsers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "First Name", "Middle Name", "Last Name", "Phone", "Address", "City", "Zip Code", "Birth Date"
            }
        ));
        jScrollPane1.setViewportView(tblUsers);

        btnAdminMenu.setText("Admin Menu");
        btnAdminMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdminMenuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 733, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(BtnAgregar)
                .addGap(18, 18, 18)
                .addComponent(BtnEditar)
                .addGap(18, 18, 18)
                .addComponent(BtnEliminar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAdminMenu)
                .addGap(54, 54, 54))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnAgregar)
                    .addComponent(BtnEditar)
                    .addComponent(BtnEliminar)
                    .addComponent(btnAdminMenu))
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Nombre: BtnAgregarActionPerformed
    // Propósito: Pedir los datos de un nuevo usuario por cuadros de diálogo e insertarlo en la base de datos.
    // PreCondiciones: La tabla users debe existir y aceptar los campos indicados; DBConnection debe conectar bien.
    // PostCondiciones: Si todo sale bien, se inserta un nuevo usuario con rol USER y se recarga la tabla de usuarios.
    // Argumentos: evt - evento que se genera cuando se presiona el botón "Agregar".
    // Valores: No devuelve valor, solo interactúa con la BD y actualiza la interfaz.
    private void BtnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAgregarActionPerformed
        // TODO add your handling code here:
        // Pedir datos por ventanitas
    String firstName  = JOptionPane.showInputDialog(this, "First name:");
    if (firstName == null) return;  // Canceló

    String middleName = JOptionPane.showInputDialog(this, "Middle name (opcional):");
    if (middleName == null) middleName = "";

    String lastName   = JOptionPane.showInputDialog(this, "Last name:");
    if (lastName == null) return;

    String phone      = JOptionPane.showInputDialog(this, "Phone (opcional):");
    if (phone == null) phone = "";

    String address    = JOptionPane.showInputDialog(this, "Address (opcional):");
    if (address == null) address = "";

    String city       = JOptionPane.showInputDialog(this, "City (opcional):");
    if (city == null) city = "";

    String zipCode    = JOptionPane.showInputDialog(this, "Zip code (opcional):");
    if (zipCode == null) zipCode = "";

    String birthDate  = JOptionPane.showInputDialog(
            this, "Birth date (YYYY-MM-DD, o dejar vacío):");
    if (birthDate == null) birthDate = "";

    // Campos necesarios para login
    String username   = JOptionPane.showInputDialog(this, "Username:");
    if (username == null || username.trim().isEmpty()) {
        JOptionPane.showMessageDialog(this, "El username no puede estar vacío.");
        return;
    }

    String password   = JOptionPane.showInputDialog(this, "Password:");
    if (password == null || password.trim().isEmpty()) {
        JOptionPane.showMessageDialog(this, "La contraseña no puede estar vacía.");
        return;
    }

    // INSERT en la BD
    String sql = "INSERT INTO users (" +
                 "first_name, middle_name, last_name, phone, address, city, zip_code, " +
                 "birth_date, username, password_hash, role" +
                 ") VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";

    try (Connection cn = DBConnection.getConnection();
         PreparedStatement ps = cn.prepareStatement(sql)) {

        ps.setString(1,  firstName);
        ps.setString(2,  middleName);
        ps.setString(3,  lastName);
        ps.setString(4,  phone);
        ps.setString(5,  address);
        ps.setString(6,  city);
        ps.setString(7,  zipCode);

        if (birthDate.isBlank()) {
            ps.setNull(8, java.sql.Types.DATE);
        } else {
            ps.setString(8, birthDate);   // formato 'YYYY-MM-DD'
        }

        ps.setString(9,  username);
        ps.setString(10, password);      
        ps.setString(11, "USER");        // todos los que se añadan desde aquí serán USER

        int rows = ps.executeUpdate();

        if (rows > 0) {
            JOptionPane.showMessageDialog(this, "Usuario agregado correctamente.");
            loadUsers(); // refrescar tabla
        } else {
            JOptionPane.showMessageDialog(this, "No se pudo agregar el usuario.");
        }

    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this,
                "Error al agregar usuario:\n" + e.getMessage());
    }
    }//GEN-LAST:event_BtnAgregarActionPerformed

    // Nombre: BtnEliminarActionPerformed
    // Propósito: Eliminar de la base de datos el usuario seleccionado en la tabla.
    // PreCondiciones: Debe haber una fila seleccionada y ese ID debe existir en la tabla users.
    // PostCondiciones: Si el usuario confirma, se elimina el registro de la BD y se actualiza la tabla.
    // Argumentos: evt - evento generado al presionar el botón "Eliminar".
    // Valores: No devuelve valor, solo borra el usuario y actualiza la vista.
    private void BtnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEliminarActionPerformed
        // TODO add your handling code here:
        int fila = tblUsers.getSelectedRow();

    if (fila == -1) {
        JOptionPane.showMessageDialog(this,
                "Selecciona un usuario de la tabla para eliminar.");
        return;
    }

    DefaultTableModel model = (DefaultTableModel) tblUsers.getModel();
    Object value = model.getValueAt(fila, 0); // Columna 0 = ID

    if (value == null) {
        JOptionPane.showMessageDialog(this,
                "No se pudo obtener el ID del usuario.");
        return;
    }

    int userId = Integer.parseInt(value.toString());

    int confirm = JOptionPane.showConfirmDialog(this,
            "¿Seguro que quieres eliminar al usuario con ID " + userId + "?",
            "Confirmar eliminación",
            JOptionPane.YES_NO_OPTION);

    if (confirm != JOptionPane.YES_OPTION) {
        return;
    }

    String sql = "DELETE FROM users WHERE user_id = ?";

    try (Connection cn = DBConnection.getConnection();
         PreparedStatement ps = cn.prepareStatement(sql)) {

        ps.setInt(1, userId);
        int rows = ps.executeUpdate();

        if (rows > 0) {
            JOptionPane.showMessageDialog(this,
                    "Usuario eliminado correctamente.");
            loadUsers(); // Recargar la tabla
        } else {
            JOptionPane.showMessageDialog(this,
                    "No se eliminó ningún usuario (verifica el ID).");
        }

    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this,
                "Error al eliminar usuario:\n" + e.getMessage());
    }
    }//GEN-LAST:event_BtnEliminarActionPerformed

    // Nombre: BtnEditarActionPerformed
    // Propósito: Permitir editar los datos básicos del usuario seleccionado y guardar los cambios en la BD.
    // PreCondiciones: Debe haber un usuario seleccionado en la tabla y la conexión a la BD debe funcionar.
    // PostCondiciones: Si todo va bien, se actualiza el registro en la BD y se recarga la tabla con los nuevos datos.
    // Argumentos: evt - evento generado al presionar el botón "Editar".
    // Valores: No devuelve valor, solo actualiza la base de datos y la tabla.
    private void BtnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEditarActionPerformed
        // TODO add your handling code here:
        int fila = tblUsers.getSelectedRow();

    if (fila == -1) {
        JOptionPane.showMessageDialog(this,
                "Selecciona un usuario de la tabla para editar.");
        return;
    }

    DefaultTableModel model = (DefaultTableModel) tblUsers.getModel();

    // Tomar los valores actuales de la fila
    Object idValue       = model.getValueAt(fila, 0); // ID
    String firstName     = (String) model.getValueAt(fila, 1);
    String middleName    = (String) model.getValueAt(fila, 2);
    String lastName      = (String) model.getValueAt(fila, 3);
    String phone         = (String) model.getValueAt(fila, 4);
    String address       = (String) model.getValueAt(fila, 5);
    String city          = (String) model.getValueAt(fila, 6);
    String zipCode       = (String) model.getValueAt(fila, 7);
    Object birthDateObj  = model.getValueAt(fila, 8);

    String birthDateStr = (birthDateObj == null) ? "" : birthDateObj.toString();

    int userId = Integer.parseInt(idValue.toString());

    // Pedir nuevos valores (prellenados con lo actual)
    firstName  = JOptionPane.showInputDialog(this, "First name:", firstName);
    if (firstName == null) return;

    middleName = JOptionPane.showInputDialog(this, "Middle name:", middleName);
    if (middleName == null) middleName = "";

    lastName   = JOptionPane.showInputDialog(this, "Last name:", lastName);
    if (lastName == null) return;

    phone      = JOptionPane.showInputDialog(this, "Phone:", phone);
    if (phone == null) phone = "";

    address    = JOptionPane.showInputDialog(this, "Address:", address);
    if (address == null) address = "";

    city       = JOptionPane.showInputDialog(this, "City:", city);
    if (city == null) city = "";

    zipCode    = JOptionPane.showInputDialog(this, "Zip code:", zipCode);
    if (zipCode == null) zipCode = "";

    birthDateStr = JOptionPane.showInputDialog(
            this, "Birth date (YYYY-MM-DD, o vacío):", birthDateStr);
    if (birthDateStr == null) birthDateStr = "";

    String sql = "UPDATE users SET " +
                 "first_name = ?, middle_name = ?, last_name = ?, " +
                 "phone = ?, address = ?, city = ?, zip_code = ?, birth_date = ? " +
                 "WHERE user_id = ?";

    try (Connection cn = DBConnection.getConnection();
         PreparedStatement ps = cn.prepareStatement(sql)) {

        ps.setString(1, firstName);
        ps.setString(2, middleName);
        ps.setString(3, lastName);
        ps.setString(4, phone);
        ps.setString(5, address);
        ps.setString(6, city);
        ps.setString(7, zipCode);

        if (birthDateStr.isBlank()) {
            ps.setNull(8, java.sql.Types.DATE);
        } else {
            ps.setString(8, birthDateStr);
        }

        ps.setInt(9, userId);

        int rows = ps.executeUpdate();

        if (rows > 0) {
            JOptionPane.showMessageDialog(this, "Usuario actualizado correctamente.");
            loadUsers(); // recargar la tabla
        } else {
            JOptionPane.showMessageDialog(this, "No se actualizó el usuario (verifica el ID).");
        }

    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this,
                "Error al actualizar usuario:\n" + e.getMessage());
    }

    }//GEN-LAST:event_BtnEditarActionPerformed

    private void btnAdminMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdminMenuActionPerformed
        // TODO add your handling code here:
        new AdminManagerScreens().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAdminMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new EditUsers().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAgregar;
    private javax.swing.JButton BtnEditar;
    private javax.swing.JButton BtnEliminar;
    private javax.swing.JButton btnAdminMenu;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblUsers;
    // End of variables declaration//GEN-END:variables
}
