/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Forms;
import database.DBConnection;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author leandra
 */
public class EditRentals extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(EditRentals.class.getName());

    /**
     * Creates new form EditRentals
     */
    public EditRentals() {
        initComponents();
        loadRentals();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        Rental_Table = new javax.swing.JTable();
        RentalReturn = new javax.swing.JButton();
        RentalAdd = new javax.swing.JButton();
        btnAdminMenu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Rentals");
        setName("rentals_frame"); // NOI18N

        Rental_Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Reservation ID", "User ID", "Username", "Movie ID", "Title", "Format", "Status", "Rented Date", "Due Date"
            }
        ));
        Rental_Table.setName("rental_table"); // NOI18N
        jScrollPane2.setViewportView(Rental_Table);

        RentalReturn.setText("Return Movie");
        RentalReturn.setName("RtrnMvie_button"); // NOI18N
        RentalReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RentalReturnActionPerformed(evt);
            }
        });

        RentalAdd.setText("Add Rental");
        RentalAdd.setName("AddRntl_button"); // NOI18N
        RentalAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RentalAddActionPerformed(evt);
            }
        });

        btnAdminMenu.setText("Admin Menu");
        btnAdminMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdminMenuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 822, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(29, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(RentalReturn)
                        .addGap(31, 31, 31)
                        .addComponent(RentalAdd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAdminMenu)
                        .addGap(47, 47, 47))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RentalReturn)
                    .addComponent(RentalAdd)
                    .addComponent(btnAdminMenu))
                .addGap(53, 53, 53))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RentalReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RentalReturnActionPerformed
        // TODO add your handling code here:
      int row = Rental_Table.getSelectedRow();
    if (row == -1) {
        JOptionPane.showMessageDialog(this,
                "Please select a rental to return.");
        return;
    }

    DefaultTableModel model = (DefaultTableModel) Rental_Table.getModel();

    int reservationId = (int) model.getValueAt(row, 0); // Reservation ID col
    int movieId       = (int) model.getValueAt(row, 3); // Movie ID col
    String format     = ((String) model.getValueAt(row, 5)).toUpperCase(); // Format col

    int confirm = JOptionPane.showConfirmDialog(this,
            "Mark this rental as RETURNED?",
            "Confirm Return", JOptionPane.YES_NO_OPTION);
    if (confirm != JOptionPane.YES_OPTION) {
        return;
    }

    adminReturnRental(reservationId, movieId, format);
    }//GEN-LAST:event_RentalReturnActionPerformed

    private void RentalAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RentalAddActionPerformed
        // TODO add your handling code here:
        NewRentalMenu usersForm = new NewRentalMenu();
        usersForm.setVisible(true);
    }//GEN-LAST:event_RentalAddActionPerformed

    private void btnAdminMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdminMenuActionPerformed
        // TODO add your handling code here:
        new AdminManagerScreens().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAdminMenuActionPerformed

    private void adminReturnRental(int reservationId, int movieId, String format) {
    Connection cn = null;
    try {
        cn = DBConnection.getConnection();
        cn.setAutoCommit(false);

        // 1) Mark reservation as RETURNED
        String sqlUpdateReservation =
            "UPDATE reservations " +
            "SET status = 'RETURNED', return_actual_at = NOW() " +
            "WHERE reservation_id = ?";
        try (PreparedStatement ps = cn.prepareStatement(sqlUpdateReservation)) {
            ps.setInt(1, reservationId);
            ps.executeUpdate();
        }

        // 2) Free the correct format in movies
        String availabilityColumn =
                format.equals("DVD") ? "available_dvd" : "available_bluray";

        String sqlUpdateMovie =
            "UPDATE movies SET " + availabilityColumn + " = 1 " +
            "WHERE movie_id = ?";
        try (PreparedStatement ps = cn.prepareStatement(sqlUpdateMovie)) {
            ps.setInt(1, movieId);
            ps.executeUpdate();
        }

        cn.commit();
        JOptionPane.showMessageDialog(this, "Rental returned successfully.");
        loadRentals();   // refresh table

    } catch (Exception ex) {
        try {
            if (cn != null) cn.rollback();
        } catch (Exception ignore) {}
        logger.log(java.util.logging.Level.SEVERE, "Admin return failed", ex);
        JOptionPane.showMessageDialog(this,
                "Error returning rental: " + ex.getMessage());
    } finally {
        try {
            if (cn != null) cn.setAutoCommit(true);
        } catch (Exception ignore) {}
    }
}
    private void loadRentals() {
    DefaultTableModel model = (DefaultTableModel) Rental_Table.getModel();
    model.setRowCount(0);  // clear existing rows

    String sql =
        "SELECT r.reservation_id, r.user_id, u.username, " +
        "       r.movie_id, m.title, r.format, r.status, " +
        "       r.reservation_date, r.return_due_at " +
        "FROM reservations r " +
        "JOIN movies m ON r.movie_id = m.movie_id " +
        "JOIN users  u ON r.user_id  = u.user_id " +   // <--- 'id' = PK from your users table
        "ORDER BY (r.status = 'PENDING') DESC, r.reservation_date DESC";

    try (Connection cn = DBConnection.getConnection();
         PreparedStatement ps = cn.prepareStatement(sql);
         ResultSet rs = ps.executeQuery()) {

        while (rs.next()) {
            model.addRow(new Object[] {
                rs.getInt("reservation_id"),
                rs.getInt("user_id"),
                rs.getString("username"),
                rs.getInt("movie_id"),
                rs.getString("title"),
                rs.getString("format"),
                rs.getString("status"),
                rs.getTimestamp("reservation_date"),
                rs.getTimestamp("return_due_at")
            });
        }

    } catch (Exception e) {
        logger.log(java.util.logging.Level.SEVERE, "Error loading rentals", e);
        JOptionPane.showMessageDialog(this,
                "Error loading rentals: " + e.getMessage());
    }
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new EditRentals().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton RentalAdd;
    private javax.swing.JButton RentalReturn;
    private javax.swing.JTable Rental_Table;
    private javax.swing.JButton btnAdminMenu;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
