/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Forms;

import database.DBConnection;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;


/**
 *
 * @author isaiahvega
 */
public class MovieBrowser extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MovieBrowser.class.getName());

    private final int currentUserId;
    private Integer selectedMovieId = null;

    // Constructor used from LoginForm / other screens
    public MovieBrowser(int userId) {
        this.currentUserId = userId;
        initComponents();
        loadAvailableMovies();   // ⬅️ we’ll create this method
        
    }

    // Optional: default constructor so NetBeans can open the form in Design
    public MovieBrowser() {
        this(-1); // -1 = no actual user, for testing/design only
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        ltPanel = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        pnlMovies = new javax.swing.JPanel();
        rtPanel = new javax.swing.JPanel();
        txtTitle = new java.awt.TextField();
        txtDirector = new java.awt.TextField();
        txtWriters = new java.awt.TextField();
        txtGenre = new java.awt.TextField();
        txtRated = new java.awt.TextField();
        txtRuntime = new java.awt.TextField();
        txtReleaseDate = new java.awt.TextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtCast = new java.awt.TextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtSynopsis = new java.awt.TextArea();
        btnHoldDvd = new javax.swing.JButton();
        btnHoldBluray = new javax.swing.JButton();
        lblPoster = new javax.swing.JLabel();
        lblDirector = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        lblWriters = new javax.swing.JLabel();
        lblGenre = new javax.swing.JLabel();
        lblRated = new javax.swing.JLabel();
        lblRuntime = new javax.swing.JLabel();
        lblReleaseDate = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jSplitPane1.setName("splitMain"); // NOI18N

        pnlMovies.setLayout(new java.awt.GridLayout(0, 2, 10, 10));
        jScrollPane4.setViewportView(pnlMovies);

        javax.swing.GroupLayout ltPanelLayout = new javax.swing.GroupLayout(ltPanel);
        ltPanel.setLayout(ltPanelLayout);
        ltPanelLayout.setHorizontalGroup(
            ltPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 392, Short.MAX_VALUE)
        );
        ltPanelLayout.setVerticalGroup(
            ltPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 765, Short.MAX_VALUE)
        );

        jSplitPane1.setLeftComponent(ltPanel);

        txtWriters.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtWritersActionPerformed(evt);
            }
        });

        jScrollPane2.setViewportView(txtCast);

        jScrollPane3.setViewportView(txtSynopsis);

        btnHoldDvd.setText("Hold DVD");
        btnHoldDvd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHoldDvdActionPerformed(evt);
            }
        });

        btnHoldBluray.setText("Hold Blu-Ray");
        btnHoldBluray.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHoldBlurayActionPerformed(evt);
            }
        });

        lblDirector.setText("Director:");

        lblTitle.setText("Title:");

        lblWriters.setText("Writers:");
        lblWriters.setToolTipText("");

        lblGenre.setText("Genre:");

        lblRated.setText("Rated:");

        lblRuntime.setText("Runtime:");

        lblReleaseDate.setText("Release Date:");

        javax.swing.GroupLayout rtPanelLayout = new javax.swing.GroupLayout(rtPanel);
        rtPanel.setLayout(rtPanelLayout);
        rtPanelLayout.setHorizontalGroup(
            rtPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rtPanelLayout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(btnHoldDvd, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(113, 113, 113)
                .addComponent(btnHoldBluray, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rtPanelLayout.createSequentialGroup()
                .addGroup(rtPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(rtPanelLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblPoster, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rtPanelLayout.createSequentialGroup()
                        .addContainerGap(46, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19)))
                .addGroup(rtPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(rtPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(rtPanelLayout.createSequentialGroup()
                            .addComponent(lblReleaseDate)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtReleaseDate, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, rtPanelLayout.createSequentialGroup()
                            .addComponent(lblRuntime)
                            .addGap(40, 40, 40)
                            .addComponent(txtRuntime, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, rtPanelLayout.createSequentialGroup()
                            .addComponent(lblRated)
                            .addGap(53, 53, 53)
                            .addComponent(txtRated, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, rtPanelLayout.createSequentialGroup()
                            .addComponent(lblGenre)
                            .addGap(53, 53, 53)
                            .addComponent(txtGenre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, rtPanelLayout.createSequentialGroup()
                            .addGroup(rtPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblDirector)
                                .addComponent(lblWriters)
                                .addComponent(lblTitle))
                            .addGap(43, 43, 43)
                            .addGroup(rtPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
                                .addComponent(txtDirector, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtWriters, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(rtPanelLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(24, 24, 24))
        );
        rtPanelLayout.setVerticalGroup(
            rtPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rtPanelLayout.createSequentialGroup()
                .addContainerGap(75, Short.MAX_VALUE)
                .addGroup(rtPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rtPanelLayout.createSequentialGroup()
                        .addGroup(rtPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(rtPanelLayout.createSequentialGroup()
                                .addGroup(rtPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(rtPanelLayout.createSequentialGroup()
                                        .addComponent(lblTitle)
                                        .addGap(13, 13, 13))
                                    .addGroup(rtPanelLayout.createSequentialGroup()
                                        .addComponent(txtTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addGroup(rtPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblWriters)
                                    .addGroup(rtPanelLayout.createSequentialGroup()
                                        .addGroup(rtPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblDirector)
                                            .addComponent(txtDirector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtWriters, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtGenre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblGenre))
                        .addGap(13, 13, 13)
                        .addGroup(rtPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblRated)
                            .addComponent(txtRated, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(rtPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtRuntime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblRuntime))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(rtPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtReleaseDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblReleaseDate)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rtPanelLayout.createSequentialGroup()
                        .addComponent(lblPoster, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(157, 157, 157)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                .addGroup(rtPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addGap(51, 51, 51)
                .addGroup(rtPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnHoldDvd, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHoldBluray, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(118, 118, 118))
        );

        jSplitPane1.setRightComponent(rtPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSplitPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSplitPane1))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtWritersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtWritersActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtWritersActionPerformed

    private void btnHoldDvdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHoldDvdActionPerformed
        // TODO add your handling code here:
        placeHold("DVD");
    }//GEN-LAST:event_btnHoldDvdActionPerformed

    private void btnHoldBlurayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHoldBlurayActionPerformed
        // TODO add your handling code here:
        placeHold("BLURAY");
    }//GEN-LAST:event_btnHoldBlurayActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MovieBrowser(1).setVisible(true));
    }
    
    private void clearDetails() {
    selectedMovieId = null;
    txtTitle.setText("");
    txtDirector.setText("");
    txtWriters.setText("");
    txtGenre.setText("");
    txtRated.setText("");
    txtRuntime.setText("");
    txtReleaseDate.setText("");
    txtCast.setText("");
    txtSynopsis.setText("");
    btnHoldDvd.setEnabled(false);
    btnHoldBluray.setEnabled(false);
}
    private void placeHold(String format) {
    if (selectedMovieId == null) {
        JOptionPane.showMessageDialog(this,
                "Please select a movie first.");
        return;
    }

    if (currentUserId <= 0) {
        JOptionPane.showMessageDialog(this,
                "This action requires a logged-in user.");
        return;
    }

    String availabilityColumn = format.equalsIgnoreCase("DVD")
            ? "available_dvd"
            : "available_bluray";

    Connection cn = null;
    try {
        cn = DBConnection.getConnection();
        cn.setAutoCommit(false); // start transaction

        // 1) Check availability and lock the row
        String checkSql = "SELECT " + availabilityColumn +
                          " FROM movies WHERE movie_id = ? FOR UPDATE";
        try (PreparedStatement psCheck = cn.prepareStatement(checkSql)) {
            psCheck.setInt(1, selectedMovieId);
            try (ResultSet rs = psCheck.executeQuery()) {
                if (!rs.next() || rs.getInt(1) == 0) {
                    cn.rollback();
                    JOptionPane.showMessageDialog(this,
                            "This format is no longer available.");
                    // refresh table just in case
                    loadAvailableMovies();
                    return;
                }
            }
        }

        // 2) Insert reservation
        // price_per_day here is hardcoded as 2.50, adjust if needed
        String insertSql =
                "INSERT INTO reservations " +
                "(user_id, movie_id, price_per_day, reservation_date, " +
                " return_due_at, additional_fees, status, format) " +
                "VALUES (?, ?, 2.50, NOW(), DATE_ADD(NOW(), INTERVAL 3 DAY), 0.00, 'PENDING', ?)";
        try (PreparedStatement psIns = cn.prepareStatement(insertSql)) {
            psIns.setInt(1, currentUserId);
            psIns.setInt(2, selectedMovieId);
            psIns.setString(3, format.toUpperCase());
            psIns.executeUpdate();
        }

        // 3) Mark that format as unavailable
        String updateSql = "UPDATE movies SET " + availabilityColumn + " = 0 WHERE movie_id = ?";
        try (PreparedStatement psUpd = cn.prepareStatement(updateSql)) {
            psUpd.setInt(1, selectedMovieId);
            psUpd.executeUpdate();
        }

        // Commit transaction
        cn.commit();

        JOptionPane.showMessageDialog(this,
                "Hold placed for " + format + " successfully.");

        // 4) Refresh table and details
        loadAvailableMovies();

        // If the movie still has at least one format available, reload its details,
        // otherwise clear the details
        String checkAgainSql = "SELECT " + availabilityColumn +
                               " FROM movies WHERE movie_id = ?";
        try (PreparedStatement psCheckAgain = cn.prepareStatement(checkAgainSql)) {
            psCheckAgain.setInt(1, selectedMovieId);
            try (ResultSet rs = psCheckAgain.executeQuery()) {
                if (rs.next() && rs.getInt(1) == 1) {
                    loadMovieDetails(selectedMovieId);
                } else {
                    // movie might have disappeared from list if both formats are gone
                    clearDetails();
                }
            }
        }

    } catch (Exception e) {
        logger.log(java.util.logging.Level.SEVERE, "Error placing hold", e);
        try {
            if (cn != null) cn.rollback();
        } catch (Exception ex) {
            logger.log(java.util.logging.Level.SEVERE, "Error rolling back", ex);
        }
        JOptionPane.showMessageDialog(this,
                "Error placing hold: " + e.getMessage());
    } finally {
        try {
            if (cn != null) cn.setAutoCommit(true);
        } catch (Exception ignore) {}
    }
}
    
     private void loadAvailableMovies() {
    pnlMovies.removeAll(); // remove previous cards

    String sql = "SELECT movie_id, title, poster_url " +
                 "FROM movies " +
                 "WHERE available_dvd = 1 OR available_bluray = 1";

    try (Connection cn = DBConnection.getConnection();
         PreparedStatement ps = cn.prepareStatement(sql);
         ResultSet rs = ps.executeQuery()) {

        while (rs.next()) {
            int movieId = rs.getInt("movie_id");
            String title = rs.getString("title");
            String posterUrl = rs.getString("poster_url"); // column in your table

            javax.swing.JPanel card = createMovieCard(movieId, title, posterUrl);
            pnlMovies.add(card);
        }

    } catch (Exception e) {
        logger.log(java.util.logging.Level.SEVERE, "Error loading movies", e);
        JOptionPane.showMessageDialog(this,
                "Error loading movies: " + e.getMessage());
    }

    pnlMovies.revalidate();
    pnlMovies.repaint();
}
     private javax.swing.JPanel createMovieCard(int movieId, String title, String posterPath) {
    javax.swing.JPanel card = new javax.swing.JPanel();
    card.setLayout(new java.awt.BorderLayout());
    card.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));

    // Poster on the card
    javax.swing.JLabel lblPosterCard = new javax.swing.JLabel();
    lblPosterCard.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

    if (posterPath != null && !posterPath.isBlank()) {
        try {
            javax.swing.ImageIcon icon;
            if (posterPath.startsWith("http://") || posterPath.startsWith("https://")) {
                java.net.URL url = new java.net.URL(posterPath);
                icon = new javax.swing.ImageIcon(url);
            } else {
                icon = new javax.swing.ImageIcon(posterPath); // local file path
            }

            java.awt.Image scaled = icon.getImage()
                    .getScaledInstance(180, 260, java.awt.Image.SCALE_SMOOTH);
            lblPosterCard.setIcon(new javax.swing.ImageIcon(scaled));
        } catch (Exception ex) {
            logger.log(java.util.logging.Level.WARNING, "Could not load poster: " + posterPath, ex);
            lblPosterCard.setText(title);
        }
    } else {
        lblPosterCard.setText(title);
    }

    // Details button
    javax.swing.JButton btnDetails = new javax.swing.JButton("Details");
    btnDetails.addActionListener(e -> loadMovieDetails(movieId));

    card.add(lblPosterCard, java.awt.BorderLayout.CENTER);
    card.add(btnDetails, java.awt.BorderLayout.SOUTH);

    return card;
}

    

    private void loadMovieDetails(int movieId) {
    String sql = "SELECT * FROM movies WHERE movie_id = ?";

    try (Connection cn = DBConnection.getConnection();
         PreparedStatement ps = cn.prepareStatement(sql)) {

        ps.setInt(1, movieId);
        try (ResultSet rs = ps.executeQuery()) {
            if (rs.next()) {
                selectedMovieId = movieId;

                txtTitle.setText(rs.getString("title"));
                txtDirector.setText(rs.getString("director"));
                txtWriters.setText(rs.getString("writers"));
                txtGenre.setText(rs.getString("genre"));
                txtRated.setText(rs.getString("rate"));
                txtRuntime.setText(String.valueOf(rs.getInt("running_time_minutes")));
                txtReleaseDate.setText(String.valueOf(rs.getDate("release_date")));
                txtCast.setText(rs.getString("cast"));
                txtSynopsis.setText(rs.getString("synopsis"));

                boolean availDvd = rs.getInt("available_dvd") == 1;
                boolean availBluray = rs.getInt("available_bluray") == 1;

                btnHoldDvd.setEnabled(availDvd);
                btnHoldBluray.setEnabled(availBluray);

                // Show big poster on the right
                String posterPath = rs.getString("poster_url");
                setLargePoster(posterPath);
            }
        }

    } catch (Exception e) {
        logger.log(java.util.logging.Level.SEVERE, "Error loading movie details", e);
        JOptionPane.showMessageDialog(this,
                "Error loading movie details: " + e.getMessage());
    }
}
private void setLargePoster(String posterPath) {
    if (posterPath == null || posterPath.isBlank()) {
        lblPoster.setIcon(null);
        lblPoster.setText("No image");
        return;
    }

    try {
        javax.swing.ImageIcon icon;
        if (posterPath.startsWith("http://") || posterPath.startsWith("https://")) {
            java.net.URL url = new java.net.URL(posterPath);
            icon = new javax.swing.ImageIcon(url);
        } else {
            icon = new javax.swing.ImageIcon(posterPath);
        }

        int w = lblPoster.getWidth() > 0 ? lblPoster.getWidth() : 250;
        int h = lblPoster.getHeight() > 0 ? lblPoster.getHeight() : 350;

        java.awt.Image scaled = icon.getImage()
                .getScaledInstance(w, h, java.awt.Image.SCALE_SMOOTH);
        lblPoster.setIcon(new javax.swing.ImageIcon(scaled));
        lblPoster.setText("");
    } catch (Exception ex) {
        logger.log(java.util.logging.Level.WARNING, "Could not load big poster: " + posterPath, ex);
        lblPoster.setIcon(null);
        lblPoster.setText("No image");
    }
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHoldBluray;
    private javax.swing.JButton btnHoldDvd;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JLabel lblDirector;
    private javax.swing.JLabel lblGenre;
    private javax.swing.JLabel lblPoster;
    private javax.swing.JLabel lblRated;
    private javax.swing.JLabel lblReleaseDate;
    private javax.swing.JLabel lblRuntime;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblWriters;
    private javax.swing.JPanel ltPanel;
    private javax.swing.JPanel pnlMovies;
    private javax.swing.JPanel rtPanel;
    private java.awt.TextArea txtCast;
    private java.awt.TextField txtDirector;
    private java.awt.TextField txtGenre;
    private java.awt.TextField txtRated;
    private java.awt.TextField txtReleaseDate;
    private java.awt.TextField txtRuntime;
    private java.awt.TextArea txtSynopsis;
    private java.awt.TextField txtTitle;
    private java.awt.TextField txtWriters;
    // End of variables declaration//GEN-END:variables
}
