/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Forms;

import database.DBConnection;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;


/**
 *
 * @author isaiahvega
 */
public class MovieBrowser extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MovieBrowser.class.getName());

    private final int currentUserId;
    private Integer selectedMovieId = null;

    // Constructor used from LoginForm / other screens
    public MovieBrowser(int userId) {
        this.currentUserId = userId;
        initComponents();
        
        // Para que el usuario no modifique
        txtTitle.setEditable(false);
        txtDirector.setEditable(false);
        txtWriters.setEditable(false);
        txtGenre.setEditable(false);
        txtRated.setEditable(false);
        txtRuntime.setEditable(false);
        txtReleaseDate.setEditable(false);
        txtCast.setEditable(false);
        txtSynopsis.setEditable(false);
        txtCost.setEditable(false);
        txtMovieID.setEditable(false);
        
        // Para que los detalles no se vean en una sola línea.
        txtCast.setLineWrap(true);
        txtCast.setWrapStyleWord(true);
        
        txtSynopsis.setLineWrap(true);
        txtSynopsis.setWrapStyleWord(true);
        
                
        loadAvailableMovies(); // we’ll create this method
        loadCurrentUserName();
        
    }

    private void loadCurrentUserName() {
    if (currentUserId <= 0) {
        lblCurrentUser.setText("Logged in as: (unknown)");
        return;
    }

    String sql = "SELECT first_name, last_name FROM users WHERE user_id = ?";

    try (Connection cn = DBConnection.getConnection();
         PreparedStatement ps = cn.prepareStatement(sql)) {

        ps.setInt(1, currentUserId);

        try (ResultSet rs = ps.executeQuery()) {
            if (rs.next()) {
                String first = rs.getString("first_name");
                String last  = rs.getString("last_name");
                String fullName = (first != null ? first : "") +
                                  " " +
                                  (last != null ? last : "");
                lblCurrentUser.setText("Logged in as: " + fullName.trim());
            } else {
                lblCurrentUser.setText("Logged in as: (user " + currentUserId + " not found)");
            }
        }

    } catch (Exception e) {
        logger.log(java.util.logging.Level.SEVERE, "Error loading user", e);
        lblCurrentUser.setText("Error loading user: " + e.getMessage());
    }
}
    // Optional: default constructor so NetBeans can open the form in Design
    public MovieBrowser() {
        this(-1); // -1 = no actual user, for testing/design only
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        ltPanel = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        pnlMovies = new javax.swing.JPanel();
        rtPanel = new javax.swing.JPanel();
        txtTitle = new java.awt.TextField();
        txtDirector = new java.awt.TextField();
        txtWriters = new java.awt.TextField();
        txtGenre = new java.awt.TextField();
        txtRated = new java.awt.TextField();
        txtRuntime = new java.awt.TextField();
        txtReleaseDate = new java.awt.TextField();
        btnHoldDvd = new javax.swing.JButton();
        btnHoldBluray = new javax.swing.JButton();
        lblPoster = new javax.swing.JLabel();
        lblDirector = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        lblWriters = new javax.swing.JLabel();
        lblGenre = new javax.swing.JLabel();
        lblRated = new javax.swing.JLabel();
        lblRuntime = new javax.swing.JLabel();
        lblReleaseDate = new javax.swing.JLabel();
        btnReturnMovie = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtCast = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtSynopsis = new javax.swing.JTextArea();
        btnLogout = new javax.swing.JButton();
        lblCurrentUser = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtCost = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtMovieID = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jSplitPane1.setName("splitMain"); // NOI18N

        pnlMovies.setToolTipText("");
        pnlMovies.setLayout(new java.awt.GridLayout(0, 2, 10, 1));
        jScrollPane4.setViewportView(pnlMovies);

        javax.swing.GroupLayout ltPanelLayout = new javax.swing.GroupLayout(ltPanel);
        ltPanel.setLayout(ltPanelLayout);
        ltPanelLayout.setHorizontalGroup(
            ltPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ltPanelLayout.createSequentialGroup()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 429, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        ltPanelLayout.setVerticalGroup(
            ltPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 862, Short.MAX_VALUE)
        );

        jSplitPane1.setLeftComponent(ltPanel);

        txtWriters.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtWritersActionPerformed(evt);
            }
        });

        btnHoldDvd.setText("Hold DVD");
        btnHoldDvd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHoldDvdActionPerformed(evt);
            }
        });

        btnHoldBluray.setText("Hold Blu-Ray");
        btnHoldBluray.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHoldBlurayActionPerformed(evt);
            }
        });

        lblDirector.setText("Director:");

        lblTitle.setText("Title:");

        lblWriters.setText("Writers:");
        lblWriters.setToolTipText("");

        lblGenre.setText("Genre:");

        lblRated.setText("Rated:");

        lblRuntime.setText("Runtime: (Minutes)");

        lblReleaseDate.setText("Release Date:");

        btnReturnMovie.setText("Return DVD/BluRay");
        btnReturnMovie.setToolTipText("");
        btnReturnMovie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReturnMovieActionPerformed(evt);
            }
        });

        jPanel1.setLayout(new java.awt.GridLayout(1, 2, 0, 10));

        txtCast.setColumns(20);
        txtCast.setRows(5);
        jScrollPane2.setViewportView(txtCast);

        jPanel1.add(jScrollPane2);

        txtSynopsis.setColumns(20);
        txtSynopsis.setRows(5);
        jScrollPane3.setViewportView(txtSynopsis);

        jPanel1.add(jScrollPane3);

        btnLogout.setText("Log Out");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        lblCurrentUser.setText("User:");

        jLabel3.setText("Cost:");

        txtCost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCostActionPerformed(evt);
            }
        });

        jLabel4.setText("Cast");

        jLabel5.setText("Synopsis");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 481, Short.MAX_VALUE)
                .addComponent(jLabel5))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addContainerGap())
        );

        jLabel1.setText("Movie Id:");

        txtMovieID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMovieIDActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout rtPanelLayout = new javax.swing.GroupLayout(rtPanel);
        rtPanel.setLayout(rtPanelLayout);
        rtPanelLayout.setHorizontalGroup(
            rtPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rtPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(rtPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(rtPanelLayout.createSequentialGroup()
                        .addComponent(lblPoster, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addGroup(rtPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(rtPanelLayout.createSequentialGroup()
                                .addGroup(rtPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(rtPanelLayout.createSequentialGroup()
                                        .addComponent(lblReleaseDate)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtReleaseDate, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, rtPanelLayout.createSequentialGroup()
                                        .addComponent(lblRuntime)
                                        .addGap(40, 40, 40)
                                        .addComponent(txtRuntime, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, rtPanelLayout.createSequentialGroup()
                                        .addComponent(lblRated)
                                        .addGap(53, 53, 53)
                                        .addComponent(txtRated, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, rtPanelLayout.createSequentialGroup()
                                        .addComponent(lblGenre)
                                        .addGap(53, 53, 53)
                                        .addComponent(txtGenre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, rtPanelLayout.createSequentialGroup()
                                        .addGroup(rtPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(rtPanelLayout.createSequentialGroup()
                                                .addGroup(rtPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(lblDirector)
                                                    .addComponent(lblWriters)
                                                    .addComponent(lblTitle))
                                                .addGap(43, 43, 43))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rtPanelLayout.createSequentialGroup()
                                                .addComponent(jLabel3)
                                                .addGap(61, 61, 61)))
                                        .addGroup(rtPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
                                            .addComponent(txtDirector, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(txtWriters, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(txtCost))))
                                .addGap(67, 67, 67))
                            .addGroup(rtPanelLayout.createSequentialGroup()
                                .addComponent(lblCurrentUser)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1))))
                    .addGroup(rtPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 555, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(rtPanelLayout.createSequentialGroup()
                            .addGroup(rtPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btnReturnMovie, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnHoldDvd, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE))
                            .addGap(106, 106, 106)
                            .addGroup(rtPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnHoldBluray, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtMovieID, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        rtPanelLayout.setVerticalGroup(
            rtPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rtPanelLayout.createSequentialGroup()
                .addGroup(rtPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(rtPanelLayout.createSequentialGroup()
                        .addGroup(rtPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(rtPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lblCurrentUser))
                            .addGroup(rtPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel1)
                                .addComponent(txtMovieID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(rtPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtCost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(rtPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(rtPanelLayout.createSequentialGroup()
                                .addGroup(rtPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(rtPanelLayout.createSequentialGroup()
                                        .addComponent(lblTitle)
                                        .addGap(13, 13, 13))
                                    .addGroup(rtPanelLayout.createSequentialGroup()
                                        .addComponent(txtTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addGroup(rtPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblWriters)
                                    .addGroup(rtPanelLayout.createSequentialGroup()
                                        .addGroup(rtPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblDirector)
                                            .addComponent(txtDirector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtWriters, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtGenre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblGenre))
                        .addGap(13, 13, 13)
                        .addGroup(rtPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblRated)
                            .addComponent(txtRated, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(rtPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtRuntime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblRuntime))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(rtPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtReleaseDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblReleaseDate)))
                    .addComponent(lblPoster, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(83, 83, 83)
                .addGroup(rtPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnHoldBluray, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHoldDvd, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(rtPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnReturnMovie, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42))
        );

        jSplitPane1.setRightComponent(rtPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1070, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSplitPane1))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtWritersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtWritersActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtWritersActionPerformed

    private void btnHoldDvdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHoldDvdActionPerformed
        // TODO add your handling code here:
        placeHold("DVD");
    }//GEN-LAST:event_btnHoldDvdActionPerformed

    private void btnHoldBlurayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHoldBlurayActionPerformed
        // TODO add your handling code here:
        placeHold("BLURAY");
    }//GEN-LAST:event_btnHoldBlurayActionPerformed

    private void btnReturnMovieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReturnMovieActionPerformed
        // TODO add your handling code here:
        RentalReturn rr = new RentalReturn(currentUserId);
    rr.setLocationRelativeTo(this);
    rr.setVisible(true);
    
    this.dispose();
    }//GEN-LAST:event_btnReturnMovieActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        new LoginForm().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void txtCostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCostActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCostActionPerformed

    private void txtMovieIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMovieIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMovieIDActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MovieBrowser(1).setVisible(true));
    }
    
    private void clearDetails() {
    selectedMovieId = null;
    txtMovieID.setText("");
    txtTitle.setText("");
    txtDirector.setText("");
    txtWriters.setText("");
    txtGenre.setText("");
    txtRated.setText("");
    txtRuntime.setText("");
    txtReleaseDate.setText("");
    txtCast.setText("");
    txtSynopsis.setText("");
    btnHoldDvd.setEnabled(false);
    btnHoldBluray.setEnabled(false);
}
    private void placeHold(String format) {
    if (selectedMovieId == null) {
        JOptionPane.showMessageDialog(this,
                "Please select a movie first.");
        return;
    }

    if (currentUserId <= 0) {
        JOptionPane.showMessageDialog(this,
                "This action requires a logged-in user.");
        return;
    }

    String availabilityColumn = format.equalsIgnoreCase("DVD")
            ? "available_dvd"
            : "available_bluray";

    Connection cn = null;
    try {
        cn = DBConnection.getConnection();
        cn.setAutoCommit(false); // start transaction

        // 1) Check availability and lock the row
        String checkSql = "SELECT " + availabilityColumn +
                          " FROM movies WHERE movie_id = ? FOR UPDATE";
        try (PreparedStatement psCheck = cn.prepareStatement(checkSql)) {
            psCheck.setInt(1, selectedMovieId);
            try (ResultSet rs = psCheck.executeQuery()) {
                if (!rs.next() || rs.getInt(1) == 0) {
                    cn.rollback();
                    JOptionPane.showMessageDialog(this,
                            "This format is no longer available.");
                    // refresh table just in case
                    loadAvailableMovies();
                    return;
                }
            }
        }

        // 2) Insert reservation
        // price_per_day here is hardcoded as 2.50, adjust if needed
        String insertSql =
                "INSERT INTO reservations " +
                "(user_id, movie_id, price_per_day, reservation_date, " +
                " return_due_at, additional_fees, status, format) " +
                "VALUES (?, ?, 2.50, NOW(), DATE_ADD(NOW(), INTERVAL 3 DAY), 0.00, 'PENDING', ?)";
        try (PreparedStatement psIns = cn.prepareStatement(insertSql)) {
            psIns.setInt(1, currentUserId);
            psIns.setInt(2, selectedMovieId);
            psIns.setString(3, format.toUpperCase());
            psIns.executeUpdate();
        }

        // 3) Mark that format as unavailable
        String updateSql = "UPDATE movies SET " + availabilityColumn + " = 0 WHERE movie_id = ?";
        try (PreparedStatement psUpd = cn.prepareStatement(updateSql)) {
            psUpd.setInt(1, selectedMovieId);
            psUpd.executeUpdate();
        }

        // Commit transaction
        cn.commit();

        JOptionPane.showMessageDialog(this,
                "Hold placed for " + format + " successfully.");

        // 4) Refresh table and details
        loadAvailableMovies();
        loadMovieDetails(selectedMovieId);

    } catch (Exception e) {
        logger.log(java.util.logging.Level.SEVERE, "Error placing hold", e);
        try {
            if (cn != null) cn.rollback();
        } catch (Exception ex) {
            logger.log(java.util.logging.Level.SEVERE, "Error rolling back", ex);
        }
        JOptionPane.showMessageDialog(this,
                "Error placing hold: " + e.getMessage());
    } finally {
        try {
            if (cn != null) cn.setAutoCommit(true);
        } catch (Exception ignore) {}
    }
}
    
     private void loadAvailableMovies() {
    pnlMovies.removeAll(); // remove previous cards

    String sql = "SELECT movie_id, title, poster_url " +
                 "FROM movies " +
                 "WHERE available_dvd = 1 OR available_bluray = 1";

    try (Connection cn = DBConnection.getConnection();
         PreparedStatement ps = cn.prepareStatement(sql);
         ResultSet rs = ps.executeQuery()) {

        while (rs.next()) {
            int movieId = rs.getInt("movie_id");
            String title = rs.getString("title");
            String posterUrl = rs.getString("poster_url"); // column in your table

            javax.swing.JPanel card = createMovieCard(movieId, title, posterUrl);
            pnlMovies.add(card);
        }

    } catch (Exception e) {
        logger.log(java.util.logging.Level.SEVERE, "Error loading movies", e);
        JOptionPane.showMessageDialog(this,
                "Error loading movies: " + e.getMessage());
    }

    pnlMovies.revalidate();
    pnlMovies.repaint();
}
     private javax.swing.JPanel createMovieCard(int movieId, String title, String posterPath) {
    javax.swing.JPanel card = new javax.swing.JPanel();
    card.setLayout(new javax.swing.BoxLayout(card, javax.swing.BoxLayout.Y_AXIS));
    card.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));

    // Poster label
    javax.swing.JLabel lblPosterCard = new javax.swing.JLabel();
    lblPosterCard.setAlignmentX(java.awt.Component.CENTER_ALIGNMENT);

    // Load poster
    if (posterPath != null && !posterPath.isBlank()) {
        try {
            javax.swing.ImageIcon icon;
            if (posterPath.startsWith("http://") || posterPath.startsWith("https://")) {
                java.net.URL url = new java.net.URL(posterPath);
                icon = new javax.swing.ImageIcon(url);
            } else {
                icon = new javax.swing.ImageIcon(posterPath);
            }

            java.awt.Image scaled = icon.getImage()
                    .getScaledInstance(180, 260, java.awt.Image.SCALE_SMOOTH);
            lblPosterCard.setIcon(new javax.swing.ImageIcon(scaled));
        } catch (Exception ex) {
            logger.log(java.util.logging.Level.WARNING, "Could not load poster: " + posterPath, ex);
            lblPosterCard.setText(title);
        }
    } else {
        lblPosterCard.setText(title);
    }

    // Details button
    javax.swing.JButton btnDetails = new javax.swing.JButton("Details");
    btnDetails.setAlignmentX(java.awt.Component.CENTER_ALIGNMENT);
    btnDetails.addActionListener(e -> loadMovieDetails(movieId));

    // Add components vertically
    card.add(lblPosterCard);
    card.add(javax.swing.Box.createVerticalStrut(6)); // spacing
    card.add(btnDetails);

    return card;
}

    

    private void loadMovieDetails(int movieId) {
    String sql = "SELECT * FROM movies WHERE movie_id = ?";

    try (Connection cn = DBConnection.getConnection();
         PreparedStatement ps = cn.prepareStatement(sql)) {

        ps.setInt(1, movieId);
        try (ResultSet rs = ps.executeQuery()) {
            if (rs.next()) {
                selectedMovieId = movieId;

                txtMovieID.setText(String.valueOf(movieId));
                txtTitle.setText(rs.getString("title"));
                txtDirector.setText(rs.getString("director"));
                txtWriters.setText(rs.getString("writers"));
                txtGenre.setText(rs.getString("genre"));
                txtRated.setText(rs.getString("rate"));
                txtRuntime.setText(String.valueOf(rs.getInt("running_time_minutes")));
                txtReleaseDate.setText(String.valueOf(rs.getDate("release_date")));
                txtCast.setText(rs.getString("cast"));
                txtSynopsis.setText(rs.getString("synopsis"));
                
                String costStr = rs.getString("costo");   // o rs.getBigDecimal("costo").toString()
                if (costStr != null) {
                    txtCost.setText(costStr);
                } else {
                    txtCost.setText("");
                }

                boolean availDvd = rs.getInt("available_dvd") == 1;
                boolean availBluray = rs.getInt("available_bluray") == 1;

                btnHoldDvd.setEnabled(availDvd);
                btnHoldBluray.setEnabled(availBluray);

                // Show big poster on the right
                String posterPath = rs.getString("poster_url");
                setLargePoster(posterPath);
            }
        }

    } catch (Exception e) {
        logger.log(java.util.logging.Level.SEVERE, "Error loading movie details", e);
        JOptionPane.showMessageDialog(this,
                "Error loading movie details: " + e.getMessage());
    }
}
private void setLargePoster(String posterPath) {
    if (posterPath == null || posterPath.isBlank()) {
        lblPoster.setIcon(null);
        lblPoster.setText("No image");
        return;
    }

    try {
        javax.swing.ImageIcon icon;
        if (posterPath.startsWith("http://") || posterPath.startsWith("https://")) {
            java.net.URL url = new java.net.URL(posterPath);
            icon = new javax.swing.ImageIcon(url);
        } else {
            icon = new javax.swing.ImageIcon(posterPath);
        }

        int w = lblPoster.getWidth() > 0 ? lblPoster.getWidth() : 250;
        int h = lblPoster.getHeight() > 0 ? lblPoster.getHeight() : 350;

        java.awt.Image scaled = icon.getImage()
                .getScaledInstance(w, h, java.awt.Image.SCALE_SMOOTH);
        lblPoster.setIcon(new javax.swing.ImageIcon(scaled));
        lblPoster.setText("");
    } catch (Exception ex) {
        logger.log(java.util.logging.Level.WARNING, "Could not load big poster: " + posterPath, ex);
        lblPoster.setIcon(null);
        lblPoster.setText("No image");
    }
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHoldBluray;
    private javax.swing.JButton btnHoldDvd;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnReturnMovie;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JLabel lblCurrentUser;
    private javax.swing.JLabel lblDirector;
    private javax.swing.JLabel lblGenre;
    private javax.swing.JLabel lblPoster;
    private javax.swing.JLabel lblRated;
    private javax.swing.JLabel lblReleaseDate;
    private javax.swing.JLabel lblRuntime;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblWriters;
    private javax.swing.JPanel ltPanel;
    private javax.swing.JPanel pnlMovies;
    private javax.swing.JPanel rtPanel;
    private javax.swing.JTextArea txtCast;
    private javax.swing.JTextField txtCost;
    private java.awt.TextField txtDirector;
    private java.awt.TextField txtGenre;
    private javax.swing.JTextField txtMovieID;
    private java.awt.TextField txtRated;
    private java.awt.TextField txtReleaseDate;
    private java.awt.TextField txtRuntime;
    private javax.swing.JTextArea txtSynopsis;
    private java.awt.TextField txtTitle;
    private java.awt.TextField txtWriters;
    // End of variables declaration//GEN-END:variables
}
