/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Forms;


import database.DBConnection;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
/**
 *
 * @author leandra
 */
public class RentalReturn extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(RentalReturn.class.getName());
    
    private final int currentUserId;
    /**
     * Creates new form Rental_Return
     */
    
    // Nombre: RentalReturn (constructor con userId)
    // Propósito: Crear la ventana de devoluciones sabiendo qué usuario está usando el sistema.
    // PreCondiciones: Debe existir un usuario logueado y se le pasa su id correctamente.
    // PostCondiciones: La pantalla de RentalReturn queda lista para que el usuario escriba el ID de la película a devolver.
    // Argumentos: userId - id del usuario que está usando la aplicación.
    // Valores: No devuelve valor.
    public RentalReturn(int userId) {
        this.currentUserId = userId;
        initComponents();
    }
    public RentalReturn(){
        this(-1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        OkButton = new javax.swing.JButton();
        CancelButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        lblFormat = new javax.swing.JLabel();
        cmbFormat = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Returns");
        setName("Returns"); // NOI18N

        OkButton.setText("OK");
        OkButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OkButtonActionPerformed(evt);
            }
        });

        CancelButton.setText("Cancel");
        CancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelButtonActionPerformed(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("Enter movie ID:");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        lblFormat.setText("Format: ");

        cmbFormat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "DVD", "BLURAY", " " }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(OkButton)
                            .addComponent(lblFormat))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CancelButton)
                    .addComponent(cmbFormat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(83, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFormat)
                    .addComponent(cmbFormat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CancelButton)
                    .addComponent(OkButton))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
                    

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    
    // Nombre: OkButtonActionPerformed
    // Propósito: Validar el ID de película que escribe el usuario, buscar su renta activa y abrir la pantalla de confirmación de devolución.
    // PreCondiciones: Debe haber un usuario logueado (currentUserId > 0) y existir la tabla reservations/movies con los campos usados en el query.
    // PostCondiciones: Si encuentra la renta pendiente, abre ReturnConfirmation con los datos correctos y cierra esta ventana.
    // Argumentos: evt - evento del botón OK.
    // Valores: No devuelve valor, pero muestra mensajes y abre/cierra ventanas según el resultado.
    private void OkButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OkButtonActionPerformed
        // TODO add your handling code here:     
        String text = jTextField1.getText().trim();
    if (text.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Please enter a movie ID.");
        return;
    }

    int movieId;
    try {
        movieId = Integer.parseInt(text);
    } catch (NumberFormatException ex) {
        JOptionPane.showMessageDialog(this, "Movie ID must be a number.");
        return;
    }

    if (currentUserId <= 0) {
        JOptionPane.showMessageDialog(this,
                "No logged-in user. Open this screen from the main app.");
        return;
    }

    // If you have a combo box for format (DVD / BLURAY), keep this:
    String format = (cmbFormat != null)
            ? (String) cmbFormat.getSelectedItem()
            : null;

    String sql =
        "SELECT r.reservation_id, r.movie_id, r.format, m.title " +
        "FROM reservations r " +
        "JOIN movies m ON r.movie_id = m.movie_id " +
        "WHERE r.user_id = ? " +          // 👈 only this user’s rentals
        "  AND r.movie_id = ? " +
        (format != null ? "  AND r.format = ? " : "") +
        "  AND r.status = 'PENDING' " +
        "ORDER BY r.reservation_date DESC " +
        "LIMIT 1";

    try (Connection cn = DBConnection.getConnection();
         PreparedStatement ps = cn.prepareStatement(sql)) {

        int idx = 1;
        ps.setInt(idx++, currentUserId);    // 👈 user filter
        ps.setInt(idx++, movieId);
        if (format != null) {
            ps.setString(idx++, format);
        }

        try (ResultSet rs = ps.executeQuery()) {
            if (!rs.next()) {
                JOptionPane.showMessageDialog(this,
                        "No active rental found for that movie under this user.");
                return;
            }

            int reservationId = rs.getInt("reservation_id");
            String dbFormat   = rs.getString("format");
            String title      = rs.getString("title");

            ReturnConfirmation rc =
                    new ReturnConfirmation(reservationId,
                                           movieId,
                                           currentUserId,
                                           dbFormat,
                                           title);
            rc.setLocationRelativeTo(this);
            rc.setVisible(true);
            this.dispose();
        }

    } catch (Exception e) {
        logger.log(java.util.logging.Level.SEVERE, "Error looking up rental", e);
        JOptionPane.showMessageDialog(this,
                "Error searching rental: " + e.getMessage());
    }
                                          
    }//GEN-LAST:event_OkButtonActionPerformed

    // Nombre: CancelButtonActionPerformed
    // Propósito: Cerrar la pantalla de devoluciones y regresar al browser de películas.
    // PreCondiciones: La clase MovieBrowser debe existir y poder mostrarse sin errores.
    // PostCondiciones: Se cierra esta ventana y se abre MovieBrowser.
    // Argumentos: evt - evento del botón Cancel.
    // Valores: No devuelve valor.
    private void CancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelButtonActionPerformed
        // TODO add your handling code here:
        new MovieBrowser().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_CancelButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new RentalReturn().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CancelButton;
    private javax.swing.JButton OkButton;
    private javax.swing.JComboBox<String> cmbFormat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lblFormat;
    // End of variables declaration//GEN-END:variables
}
