/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Forms;
import database.DBConnection;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
/**
 *
 * @author leandra
 */
public class ReturnConfirmation extends javax.swing.JFrame {
    
        private static final java.util.logging.Logger logger =
            java.util.logging.Logger.getLogger(ReturnConfirmation.class.getName());

    private int reservationId;
    private int movieId;
    private int userId;
    private String format;
    private String movieTitle;
    /**
     * Creates new form Return_Confirmation
     */
    public ReturnConfirmation() {
        initComponents();
    }
    
    public ReturnConfirmation(int reservationId,
                          int movieId,
                          int userId,
                          String format,
                          String movieTitle) {
    this.reservationId = reservationId;
    this.movieId = movieId;
    this.userId = userId;
    this.format = format;
    this.movieTitle = movieTitle;
    initComponents();
    loadReturnDetails();
}
    private void loadReturnDetails() {
    // These labels are guesses based on your form:
    // jLabel8, 10, 11, 12, 14, 13, 15 are on the right side.
    // Adjust if they represent something different in your design.

    jLabel8.setText(movieTitle);               // Movie:
    jLabel10.setText("User ID: " + userId);    // Customer:
    jLabel11.setText(format);                  // Format:

    String sql = "SELECT reservation_date, return_due_at " +
                 "FROM reservations WHERE reservation_id = ?";

    try (Connection cn = DBConnection.getConnection();
         PreparedStatement ps = cn.prepareStatement(sql)) {

        ps.setInt(1, reservationId);
        try (ResultSet rs = ps.executeQuery()) {
            if (rs.next()) {
                jLabel12.setText(String.valueOf(rs.getTimestamp("reservation_date"))); // Rent date
                jLabel14.setText(String.valueOf(rs.getTimestamp("return_due_at")));    // Due date
                // You can calculate extra things like late fees here if needed
            }
        }
    } catch (Exception e) {
        logger.log(java.util.logging.Level.SEVERE, "Error loading return details", e);
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CompleteReturnButton = new javax.swing.JButton();
        CancelReturnButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        CompleteReturnButton.setText("Complete Return");
        CompleteReturnButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CompleteReturnButtonActionPerformed(evt);
            }
        });

        CancelReturnButton.setText("Cancel Return");
        CancelReturnButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelReturnButtonActionPerformed(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("Movie:");

        jLabel2.setText("Customer:");

        jLabel3.setText("Rented On:");

        jLabel4.setText("Returned On:");

        jLabel5.setText("Cost:");

        jLabel6.setText("Total Days:");

        jLabel7.setText("Total Cost:");

        jLabel8.setText("import db");

        jLabel10.setText("import db");

        jLabel11.setText("import db");

        jLabel12.setText("import db");

        jLabel13.setText("import db");

        jLabel14.setText("import db");

        jLabel15.setText("import cost mult by days");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(CompleteReturnButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CancelReturnButton)
                .addContainerGap(126, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addGap(0, 72, Short.MAX_VALUE)))
                .addGap(22, 22, 22))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel13))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel15))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CompleteReturnButton)
                    .addComponent(CancelReturnButton))
                .addGap(17, 17, 17))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CompleteReturnButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CompleteReturnButtonActionPerformed
        // TODO add your handling code here:
        /* removes entire row from user rental tab, research database deletion via java code*/
        Connection cn = null;
    try {
        cn = DBConnection.getConnection();
        cn.setAutoCommit(false);

        // 1) Mark reservation as returned
        String sqlRes =
                "UPDATE reservations " +
                "SET status = 'RETURNED', return_actual_at = NOW() " +
                "WHERE reservation_id = ? AND user_id = ?";
        try (PreparedStatement psRes = cn.prepareStatement(sqlRes)) {
            psRes.setInt(1, reservationId);
            psRes.setInt(2, userId);
            int updated = psRes.executeUpdate();
            if (updated == 0) {
                cn.rollback();
                JOptionPane.showMessageDialog(this,
                        "No matching active reservation found.");
                return;
            }
        }

        // 2) Make the specific format available again
        String column = "DVD".equalsIgnoreCase(format)
                ? "available_dvd"
                : "available_bluray";

        String sqlMovie =
                "UPDATE movies SET " + column + " = 1 WHERE movie_id = ?";
        try (PreparedStatement psMovie = cn.prepareStatement(sqlMovie)) {
            psMovie.setInt(1, movieId);
            psMovie.executeUpdate();
        }

        cn.commit();
        
        JOptionPane.showMessageDialog(this, "Movie returned successfully.");
        
        MovieBrowser browser = new MovieBrowser(userId);
        browser.setLocationRelativeTo(null);   // center on screen (optional)
        browser.setVisible(true);

        
        this.dispose();

    } catch (Exception e) {
        if (cn != null) {
            try { cn.rollback(); } catch (Exception ex) { /* ignore */ }
        }
        logger.log(java.util.logging.Level.SEVERE, "Error completing return", e);
        JOptionPane.showMessageDialog(this,
                "Error completing return: " + e.getMessage());
    } finally {
        if (cn != null) {
            try { cn.setAutoCommit(true); } catch (Exception ex) { /* ignore */ }
        }
    }
    }//GEN-LAST:event_CompleteReturnButtonActionPerformed

    private void CancelReturnButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelReturnButtonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_CancelReturnButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ReturnConfirmation().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CancelReturnButton;
    private javax.swing.JButton CompleteReturnButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    // End of variables declaration//GEN-END:variables
}
